### ISSUE TITLE
dfget panic when use it to download file in p2p pattern.

### ISSUE THREAD

**Issue by zcc35357949** [dragonflyoss/Dragonfly#1410]
### Ⅰ. Issue Description
l use the below command to download file in p2p pattern.
```
./dfget -u http://172.16.17.24:8000/go1.12.9.linux-amd64.tar.gz -o /root/go1.12.9.linux-amd64.tar.gz --home "/data/docker/.small-dragonfly"  --pattern p2p -s
 800MB --totallimit 800MB --node 172.16.17.24:8002,172.16.17.24:8002 --verbose
```

dfget panic info:
```
dfget version:
workspace:/data/docker/.small-dragonfly
sign:28934-1593952426.364
client:172.16.17.24 connected to node:172.16.17.24:8002
start download by dragonfly...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x94c8d3]

goroutine 39 [running]:
github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader.(*Piece).RawContent(0xc00050a080, 0xc000826400, 0x0)
        /data/app/src/github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader/piece.go:67 +0x33
github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader.writePieceToFile(0xc00050a080, 0xc000826488, 0xc0005c3a70, 0x9, 0x5, 0x9d4eee)
        /data/app/src/github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader/client_writer.go:248 +0x109
github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader.(*TargetWriter).write(...)
        /data/app/src/github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader/target_writer.go:125
github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader.(*TargetWriter).Run(0xc000330620, 0xbcefe0, 0xc0000c5b00)
        /data/app/src/github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader/target_writer.go:102 +0xf5
created by github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader.(*ClientWriter).Run
        /data/app/src/github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader/client_writer.go:166 +0x64
```

### Ⅱ. Describe what happened
dfget command panic

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
when the output file path(`--output`) and home directory(`--home`) are mounted under different disk device, p2p download process will panic.

### Ⅵ. Environment:

- dragonfly version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jim3ma** [comment]
Please try #1418 fix
