### ISSUE TITLE
how could I deploy fileserver and supernode on different machines?

### ISSUE THREAD

**Issue by Silocean** [dragonflyoss/Dragonfly#307]
If I use multi supernodes and deply fileservers and supernodes on the same machines, do I need to place same files on all the machines? Or how could I deploy fileserver and supernode on different machines?

**Comment by allencloud** [comment]
Thanks for your feedback. @Silocean 
Before answering your question, I wish that you have seen the issue https://github.com/dragonflyoss/Dragonfly/issues/291. If not, please join us via the way provided in that issue.

Back to the question. What is the use case of using multi supernodes? Could you be more specific?

In addition, for supernode, it only needs to know the file's downloading link, regardless of the location where fileserver and supernode are deployed.

> If I use multi supernodes and deply fileservers and supernodes on the same machines, do I need to place same files on all the machines?

Actually I cannot quite follow you. Could you be in details?

**Comment by Silocean** [comment]
I tried to deploy supernode and fileserver on two machines(192.168.1.99, 192.168.1.132) separately.
- On the supernode machine(192.168.1.99), I started a supernode.
- On the fileserver machine(192.168.1.132), I started the nginx.
nginx.conf
```
server {
        listen 8001;
        location / {
            root /home/admin/supernode/repo;
       }
    }
    server {
        listen 8002;
        location / {
            proxy_pass http://192.168.1.99:8080;
        }
    }
```
And when I execute `dfget -u 'http://192.168.1.132:8001/fm_ltr_model_ct_a.txt' -o ./fm_ltr_model_ct_a.txt`, got error bellow:
```
[2019-01-07 17:32:06,986] INFO sign:18947-1546853526.986 lineno:51 : cmd params:Namespace(callsystem=None, console=False, dfdaemon=False, filter=None, header=None, identifier=None, locallimit=None, md5=None, node=None, notbs=False, output='/root/fm_ltr_model_ct_a.txt', pattern=None, showbar=False, timeout=None, totallimit=None, url='http://192.168.1.132:8001/fm_ltr_model_ct_a.txt', version=False),python version:sys.version_info(major=2, minor=7, micro=11, releaselevel='final', serial=0)
[2019-01-07 17:32:06,988] INFO sign:18947-1546853526.986 lineno:107 : target file path:/root/fm_ltr_model_ct_a.txt
[2019-01-07 17:32:06,990] ERROR sign:18947-1546853526.986 lineno:34 : connect to ip:192.168.1.99 port:8002 fail
Traceback (most recent call last):
  File "/root/df-client/component/netutil.py", line 31, in check_connect
    s.connect((ip, port))
  File "/usr/local/python2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
[2019-01-07 17:32:06,990] ERROR sign:18947-1546853526.986 lineno:34 : connect to ip:192.168.1.99 port:8002 fail
Traceback (most recent call last):
  File "/root/df-client/component/netutil.py", line 31, in check_connect
    s.connect((ip, port))
  File "/usr/local/python2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
[2019-01-07 17:32:06,991] ERROR sign:18947-1546853526.986 lineno:136 : init fail but try back down
Traceback (most recent call last):
  File "/root/df-client/dfget", line 128, in <module>
    register_result = env.init()
  File "/root/df-client/env.py", line 126, in init
    back_reason = constants.REASON_NODE_EMPTY
AttributeError: 'module' object has no attribute 'REASON_NODE_EMPTY'
[2019-01-07 17:32:06,991] INFO sign:18947-1546853526.986 lineno:604 : start download fm_ltr_model_ct_a.txt from the source station
[2019-01-07 17:32:27,604] INFO sign:18947-1546853526.986 lineno:109 : move src:/root/tmp6M0s7F.backsource to dst:/root/fm_ltr_model_ct_a.txt result:True cost:0.037
[2019-01-07 17:32:27,652] INFO sign:18947-1546853526.986 lineno:94 : |UNKNOWN|http://192.168.1.132:8001/fm_ltr_model_ct_a.txt|211450700|211450700|UNKNOWN|UNKNOWN|20.666|
[2019-01-07 17:32:27,652] INFO sign:18947-1546853526.986 lineno:111 : download SUCCESS cost:20.667s length:211450700 reason:5
```
But when I deploy supernode and fileserver on one machine, everyting goes right. Is there something wrong with my configure?

**Comment by Starnop** [comment]
@Silocean Could you describe your problem in more details?  If there is no doubt, please close this issue. THX.
