### ISSUE TITLE
Dragonfly does not work

### ISSUE THREAD

**Issue by supereagle** [dragonflyoss/Dragonfly#451]
### Ⅱ. Describe what happened

Follow [Dragonfly Quick Start](https://github.com/dragonflyoss/Dragonfly/tree/master/docs/quick_start) to install Dragonfly, but it does not work.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

Env:

* SuperNode: 192.168.21.103
* Clients: 192.168.21.102, 192.168.21.101

Installation:

* SuperNode

```
$ docker run --name dragonfly-supernode --restart=always -d -p 8001:8001 -p 8002:8002 registry.cn-hangzhou.aliyuncs.com/dragonflyoss/supernode:0.3.0
```

* Clients

```
$ cat <<EOD >/etc/dragonfly.conf
[node]
address=192.168.21.103
EOD
$ docker run --name dragonfly-dfclient --restart=always -d -p 65001:65001 -v /root/.small-dragonfly:/root/.small-dragonfly -v /etc/dragonfly.conf:/etc/dragonfly.conf dragonflyoss/dfclient:v0.3.0 --registry=https://registry.xx.com
# Add "registry-mirrors": ["http://127.0.0.1:65001"] in /etc/docker/daemon.json
$ systemctl restart docker 
```
Test:

I can pull images on client node, but there is on datas and logs from Dragonfly.

```
$ du -sh /root/.small-dragonfly/dfdaemon/data/
0	/root/.small-dragonfly/dfdaemon/data/

$ cat /root/.small-dragonfly/logs/dfdaemon.log
2019-03-15 12:31:22.357 INFO sign:1 : init...
2019-03-15 12:31:22.361 INFO sign:1 : rotate log routine start...
2019-03-15 12:31:22.396 INFO sign:1 : dfget version:
2019-03-15 12:31:22.396 ERRO sign:1 : init properties failed:open /etc/dragonfly/dfdaemon.yml: no such file or directory
2019-03-15 12:31:22.397 INFO sign:1 : init properties:{"Registries":[{"Schema":"https","Host":"cargo.caicloudprivatetest.com","Certs":null,"Regx":"(^localhost$)|(^127.0.0.1$)|(^127.0.0.1$)"}]}
2019-03-15 12:31:22.397 INFO sign:1 : init finish
2019-03-15 12:31:22.397 INFO sign:1 : start dfdaemon param: &{DfPath:/dfclient/dfget DFRepo:/root/.small-dragonfly/dfdaemon/data/ RateLimit:20M CallSystem:com_ops_dragonfly URLFilter:Signature&Expires&OSSAccessKeyId Notbs:true MaxProcs:4 Version:false Verbose:false HostIP:127.0.0.1 Port:65001 Registry:https://cargo.caicloudprivatetest.com DownRule: CertFile: KeyFile: TrustHosts:[] ConfigPath:/etc/dragonfly/dfdaemon.yml}
2019-03-15 12:31:22.397 INFO sign:1 : launch dfdaemon http server on 127.0.0.1:65001
2019-03-15 12:33:22.398 INFO sign:1 : scan repo and clean expired files
2019-03-15 12:33:22.399 INFO sign:1 : ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file
2019-03-15 12:35:22.400 INFO sign:1 : scan repo and clean expired files
2019-03-15 12:35:22.401 INFO sign:1 : ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file
2019-03-15 12:37:22.403 INFO sign:1 : scan repo and clean expired files
2019-03-15 12:37:22.404 INFO sign:1 : ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file

$ docker logs -f --tail 50 dragonfly-dfclient
# there is no log from dfclient
```

### Ⅵ. Environment:

- dragonfly version: v0.3.0
- OS (e.g. from /etc/os-release): Linux
- Kernel (e.g. `uname -a`): Linux 3.10.0-693.el7.x86_64
- Install tools:
- Others:

**Comment by lowzj** [comment]
Could you paste some related logs of docker daemon?

**Comment by anjia0532** [comment]
mee too

**Comment by anjia0532** [comment]
$ docker logs -f --tail 50 dragonfly-dfclient
2019/03/23 09:29:40 http: proxy error: dial tcp: i/o timeout
2019/03/23 09:34:08 http: proxy error: dial tcp: i/o timeout
2019/03/23 09:34:18 http: proxy error: dial tcp: i/o timeout
2019/03/23 09:35:17 http: proxy error: dial tcp: i/o timeout

**Comment by lowzj** [comment]
It seems that the requests from docker daemon are not passed through dfdaeon. Could you please paste more detailed logs?

**Comment by anjia0532** [comment]
ok.
## my env

### Dragonfly
supernode : 192.168.0.44
client: 192.168.0.40

### os env
ubuntu 16.04.6LTS x86_64 *2（supernode and client）
docker 17.06.2-ce

## steps
### supernode (ip 192.168.0.44)
ref https://github.com/dragonflyoss/Dragonfly/releases/tag/v0.3.0
```bash
$ cat <<EOD >/etc/docker/daemon.json
{
"registry-mirrors": ["https://xxxx.mirror.aliyuncs.com"] 
}
EOD
$ systemctl restart docker 
## add aliyun mirror to supernode https://cr.console.aliyun.com/cn-hangzhou/instances/mirrors

$ docker run --name dragonfly-supernode --restart=always -d -p 8001:8001 -p 8002:8002 registry.cn-hangzhou.aliyuncs.com/dragonflyoss/supernode:0.3.0
```

### client(ip 192.168.0.40)
```bash
$ cat <<EOD >/etc/dragonfly.conf
[node]
address=192.168.0.44
EOD
$ docker run --name dragonfly-dfclient --restart=always -d -p 65001:65001 -v /root/.small-dragonfly:/root/.small-dragonfly -v /etc/dragonfly.conf:/etc/dragonfly.conf dragonflyoss/dfclient:v0.3.0 --registry=https://index.docker.io
$ cat <<EOD >/etc/docker/daemon.json
{
"registry-mirrors": ["http://127.0.0.1:65001"]
}
EOD
$ systemctl restart docker 
```

## Test
ssh to clinet node (192.168.0.6) ,install iftop tools

terminal1 monitor network

```bash
$ apt install iftop -y
$ iftop
```

terminal2 pull large image(3Gb)
```bash
$ docker pull anjia0532/kubeflow-images-public.tensorflow-1.6.0-notebook-gpu:v20180604-b3733835
```

supernode server
![image](https://user-images.githubusercontent.com/15098916/54892773-c886bd80-4eed-11e9-94d3-b8bb19ea7783.png)

clinet server
![image](https://user-images.githubusercontent.com/15098916/54892742-a725d180-4eed-11e9-8277-c4edd3c87148.png)

```bash
$ docker logs -f --tail 50 dragonfly-dfclient
2019/03/25 03:00:04 http: proxy error: dial tcp: i/o timeout
2019/03/25 03:02:05 http: proxy error: dial tcp: i/o timeout

$ cat /root/.small-dragonfly/logs/dfdaemon.log
2019-03-25 02:50:10.374 INFO sign:1 : init...
2019-03-25 02:50:10.374 INFO sign:1 : rotate log routine start...
2019-03-25 02:50:10.378 INFO sign:1 : dfget version:
2019-03-25 02:50:10.378 ERRO sign:1 : init properties failed:open /etc/dragonfly/dfdaemon.yml: no such file or directory
2019-03-25 02:50:10.378 INFO sign:1 : init properties:{"Registries":[{"Schema":"https","Host":"index.docker.io","Certs":null,"Regx":"(^localhost$)|(^127.0.0.1$)|(^127.0.0.1$)"}]}
2019-03-25 02:50:10.378 INFO sign:1 : init finish
2019-03-25 02:50:10.378 INFO sign:1 : start dfdaemon param: &{DfPath:/dfclient/dfget DFRepo:/root/.small-dragonfly/dfdaemon/data/ RateLimit:20M CallSystem:com_ops_dragonfly URLFilter:Signature&Expires&OSSAccessKeyId Notbs:true MaxProcs:4 Version:false Verbose:false HostIP:127.0.0.1 Port:65001 Registry:https://index.docker.io DownRule: CertFile: KeyFile: TrustHosts:[] ConfigPath:/etc/dragonfly/dfdaemon.yml}
2019-03-25 02:50:10.390 INFO sign:1 : launch dfdaemon http server on 127.0.0.1:65001
2019-03-25 02:52:10.379 INFO sign:1 : scan repo and clean expired files
2019-03-25 02:52:10.379 INFO sign:1 : ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file
2019-03-25 02:54:10.379 INFO sign:1 : scan repo and clean expired files
2019-03-25 02:54:10.379 INFO sign:1 : ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file
2019-03-25 02:56:10.379 INFO sign:1 : scan repo and clean expired files
2019-03-25 02:56:10.380 INFO sign:1 : ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file
2019-03-25 02:58:10.380 INFO sign:1 : scan repo and clean expired files
2019-03-25 02:58:10.380 INFO sign:1 : ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file
2019-03-25 03:00:10.381 INFO sign:1 : scan repo and clean expired files
2019-03-25 03:00:10.381 INFO sign:1 : ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file
2019-03-25 03:02:10.390 INFO sign:1 : scan repo and clean expired files
2019-03-25 03:02:10.390 INFO sign:1 : ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file
2019-03-25 03:04:10.391 INFO sign:1 : scan repo and clean expired files
2019-03-25 03:04:10.391 INFO sign:1 : ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file
2019-03-25 03:06:10.391 INFO sign:1 : scan repo and clean expired files
2019-03-25 03:06:10.391 INFO sign:1 : ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file
```

follow https://d7y.io/zh-cn/blog/deploy-dragonfly-on-k8s.html
change supernode image to hub.c.163.com/hzlilanqing/supernode:0.3.0
change client image to hub.c.163.com/hzlilanqing/dfdaemon:0.2.0
it's work!!!
so Why?

**Comment by lowzj** [comment]
Could you please add debug parameter `--verbose` when you start dfdaemon?

```bash
docker run --name dragonfly-dfclient --restart=always -d -p 65001:65001 -v /root/.small-dragonfly:/root/.small-dragonfly -v /etc/dragonfly.conf:/etc/dragonfly.conf dragonflyoss/dfclient:v0.3.0 --registry=https://index.docker.io --verbose
```

**Comment by anjia0532** [comment]
@supereagle [012-P2P加速Docker镜像分发(阿里Dragonfly)](https://juejin.im/post/5c98a8e9f265da60e346fe04)

**Comment by supereagle** [comment]
> @supereagle [012-P2P加速Docker镜像分发(阿里Dragonfly)](https://juejin.im/post/5c98a8e9f265da60e346fe04)

@anjia0532 Follow your blog, but still failed. There is no error log from dragonfly-dfclient even after add `--verbose`, so I have no idea what happened.

**Comment by anjia0532** [comment]
1. can u set -Dsupernode.advertiseIp=supernode ip when u startup supernode server?
2. dragonflyoss/dfclient startup registry is index.docker.io ? private registry addr (like harbor)? chinese mirrors?
3. docker run  or deploy k8s?

**Comment by supereagle** [comment]
> * can u set -Dsupernode.advertiseIp=supernode ip when u startup supernode server( `  cat ${supernode's logs dir}/app.log |grep "use ip"`)?

supernode has error:
```
$ tail -n 150 /data/dragonfly/supernode/logs/app.log
2019-03-29 04:53:16.555  INFO 9 --- [main] c.a.d.supernode.SuperNodeStarter         : Starting SuperNodeStarter on 13ee398b750c with PID 9 (/supernode.jar started by root in /)
2019-03-29 04:53:16.560  INFO 9 --- [main] c.a.d.supernode.SuperNodeStarter         : No active profile set, falling back to default profiles: default
2019-03-29 04:53:19.081  INFO 9 --- [main] c.a.d.s.config.SupernodeProperties       : cluster members: [{"downloadPort":8002,"ip":"localhost","registerPort":8001}]
2019-03-29 04:53:19.088  INFO 9 --- [main] c.a.d.s.common.util.MonitorService       : available processors count is 4
2019-03-29 04:53:19.145 ERROR 9 --- [Thread-2] c.a.d.s.common.util.MonitorService       : process fields:null error

java.io.IOException: Cannot run program "tsar": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.alibaba.dragonfly.supernode.common.util.MonitorService$1.run(MonitorService.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 common frames omitted

2019-03-29 04:53:20.130  INFO 9 --- [main] c.a.d.supernode.SuperNodeStarter         : Started SuperNodeStarter in 4.092 seconds (JVM running for 5.055)
```

> * dragonflyoss/dfclient startup registry is index.docker.io ? private registry addr (like harbor)? chinese mirrors?

Have tested index.docker.io, private registry addr and chinese mirrors `https://registry.docker-cn.com`

> * docker run  or deploy k8s?

docker run

**Comment by anjia0532** [comment]
ignore tsar error,but your supernode.advertiseIp is localhost? It should be private/public ip(like 192.168.21.103)
`docker run registry.cn-hangzhou.aliyuncs.com/dragonflyoss/supernode:0.3.0 -Dsupernode.advertiseIp=192.168.21.103`

**Comment by supereagle** [comment]
I have added `supernode.advertiseIp`. At the same time, your command also can not handle this param.

**Comment by anjia0532** [comment]
```bash
# docker inspect dragonfly-supernode
---
output msg
[
    {
        "Id": "e39b71c86b387421ff5225962fa96839c91c38341446a232d7eb85e4f226cc53",
        "Created": "2019-03-29T03:33:32.175875515Z",
        "Path": "/.r/r",
        "Args": [
            "/bin/sh",
            "-c",
            "/root/start.sh $0 $@",
            "-Dsupernode.advertiseIp=192.168.21.103"
        ],
....

# cat app.log
2019-03-29 08:03:10.523 INFO  [      main] c.d.d.s.SuperNodeStarter       - Starting SuperNodeStarter on e39b71c86b38 with PID 14 (/supernode.jar started by root in /)
2019-03-29 08:03:10.526 INFO  [      main] c.d.d.s.SuperNodeStarter       - No active profile set, falling back to default profiles: default
2019-03-29 08:03:12.084 INFO  [      main] c.d.d.s.c.SupernodeProperties  - init local ip of supernode, use ip:192.168.21.103
2019-03-29 08:03:12.193 INFO  [      main] c.d.d.s.c.SupernodeProperties  - cluster members: [{"downloadPort":8001,"ip":"localhost","registerPort":8002}]
2019-03-29 08:03:12.200 INFO  [      main] c.d.d.s.c.util.MonitorService  - available processors count is 1
2019-03-29 08:03:12.208 ERROR [  Thread-2] c.d.d.s.c.util.MonitorService  - process fields:null error
```

this line tell u what's supernode ip.
```
2019-03-29 08:03:12.084 INFO  [      main] c.d.d.s.c.SupernodeProperties  - init local ip of supernode, use ip:192.168.21.103
```

**Comment by supereagle** [comment]
@anjia0532  Thanks for your help, it works now.

**Comment by xzy256** [comment]
我也遇到类似问题，参照博客[012-P2P加速Docker镜像分发(阿里Dragonfly)](https://juejin.im/post/5c98a8e9f265da60e346fe04) 还是有问题，
supernode和client 一直打印如下字样。@supereagle你是怎么解决的
```
2019-07-10 09:09:34.086 INFO sign:1 : scan repo and clean expired files
2019-07-10 09:09:34.086 INFO sign:1 : ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file
```

**Comment by supereagle** [comment]
> supernode和client 一直打印如下字样。@supereagle你是怎么解决的

It is the log of cleaning cached datas, which can be ignored.

**Comment by xzy256** [comment]
Thanks. I config `http-proxy.conf`, when i pull one image, i got `Error: Status 403 trying to pull repository xx/xx: "no matched registry for xxx.xxx"` error.  Waht should i do next?

**Comment by anjia0532** [comment]
@xzy256  3.x? or 4.x?
