### ISSUE TITLE
Unable to download private images with authentication

### ISSUE THREAD

**Issue by anjia0532** [dragonflyoss/Dragonfly#463]
## Experimental environment

// ## 实验环境 

### server

// ### 主机 

| type | sys | ip | docker version | 
| --- | --- | --- | --- |
| supernode | Ubuntu Server 16.04.6 LTS X64 | 192.168.0.75 | 17.06.2~ce-0~ubuntu |
| clinet1 | Ubuntu Server 16.04.6 LTS X64 | 192.168.0.76 | 17.06.2~ce-0~ubuntu |
| clinet2 | Ubuntu Server 16.04.6 LTS X64 | 192.168.0.77 | 17.06.2~ce-0~ubuntu |

### registry
This time, taking Aliyun Private Mirror Library as an example, it can be opened through https://cr.console.aliyun.com/cn-qingdao/instances/repositories.

// 本次以阿里云私有镜像库为例，可以通过 https://cr.console.aliyun.com/cn-qingdao/instances/repositories 进行开通。 

// ## supernode 步骤 

## supernode

```bash
root@d7y-1:~# docker run --name dragonfly-supernode --restart=always -d -p 8001:8001 -p 8002:8002 -v /data/dragonfly/supernode:/home/admin/supernode registry.cn-hangzhou.aliyuncs.com/dragonflyoss/supernode:0.3.0 -Dsupernode.advertiseIp=192.168.0.75
root@d7y-1:~# docker ps
CONTAINER ID        IMAGE                                                            COMMAND                  CREATED              STATUS              PORTS                              NAMES
be7fb931db0b        registry.cn-hangzhou.aliyuncs.com/dragonflyoss/supernode:0.3.0   "/bin/sh -c '/root..."   About a minute ago   Up About a minute   0.0.0.0:8001-8002->8001-8002/tcp   dragonfly-supernode
root@d7y-1:/data/dragonfly/supernode/logs# cat app.log 
2019-03-30 01:04:40.065 INFO  [      main] c.d.d.s.SuperNodeStarter       - Starting SuperNodeStarter on be7fb931db0b with PID 9 (/supernode.jar started by root in /)
2019-03-30 01:04:40.069 INFO  [      main] c.d.d.s.SuperNodeStarter       - No active profile set, falling back to default profiles: default
2019-03-30 01:04:42.151 INFO  [      main] c.d.d.s.c.SupernodeProperties  - init local ip of supernode, use ip:192.168.0.75
2019-03-30 01:04:42.253 INFO  [      main] c.d.d.s.c.SupernodeProperties  - cluster members: [{"downloadPort":8001,"ip":"localhost","registerPort":8002}]
2019-03-30 01:04:42.263 INFO  [      main] c.d.d.s.c.util.MonitorService  - available processors count is 4
2019-03-30 01:04:42.272 ERROR [  Thread-2] c.d.d.s.c.util.MonitorService  - process fields:null error
java.io.IOException: Cannot run program "tsar": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.dragonflyoss.dragonfly.supernode.common.util.MonitorService$1.run(MonitorService.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 common frames omitted
2019-03-30 01:04:43.507 INFO  [      main] c.d.d.s.SuperNodeStarter       - Started SuperNodeStarter in 3.906 seconds (JVM running for 4.59)
2019-03-30 01:04:49.472 INFO  [  spring-1] c.d.d.s.s.p.PreheatServiceImpl - deleteExpiresPreheatTask, count:0
```
从 `2019-03-30 01:04:42.151 INFO  [      main] c.d.d.s.c.SupernodeProperties  - init local ip of supernode, use ip:192.168.0.75` 看，启动ip设置成功.
```bash
// Enter your Aliyun account, password
//输入你的阿里云账号，密码 

root@d7y-2:~# docker login https://registry.cn-qingdao.aliyuncs.com 
Username: 
Password: 
Login Succeeded
root@d7y-1:/data/dragonfly/supernode/logs# docker pull nginx:alpine
root@d7y-1:/data/dragonfly/supernode/logs# docker tag nginx:alpine registry.cn-qingdao.aliyuncs.com/d7y-test/nginx:alpine
root@d7y-1:/data/dragonfly/supernode/logs# docker push registry.cn-qingdao.aliyuncs.com/d7y-test/nginx:alpine
alpine: digest: sha256:857e6f195df0e9b497be0c7fad0f013126407aaeb71edcef66a24e8b990d94b3 size: 1153
```
### dfdaemon
The following commands are executed on two clients.

// 在两台client上分别执行如下命令。 

```bash
root@d7y-2:~# cat <<EOD >/etc/dragonfly.conf
[node]
address=192.168.0.75
EOD
root@d7y-2:~# docker run --name dragonfly-dfclient --restart=always -d -p 65001:65001 -v /root/.small-dragonfly:/root/.small-dragonfly -v /etc/dragonfly.conf:/etc/dragonfly.conf dragonflyoss/dfclient:v0.3.0 --registry=https://registry.cn-qingdao.aliyuncs.com  --ratelimit 100M
Unable to find image 'dragonflyoss/dfclient:v0.3.0' locally
v0.3.0: Pulling from dragonflyoss/dfclient
169185f82c45: Pull complete 
f58f64214283: Pull complete 
bd8f062dc2d2: Pull complete 
Digest: sha256:5bcabd5b34f4da0c2d489c8f99a23a401fb9ec57e54d4fa90457a93c5a85371f
Status: Downloaded newer image for dragonflyoss/dfclient:v0.3.0
b491e90489a584119b82ca934cf2ae087abc136f7f9de3542e14fb12bc1c7512
root@d7y-2:~# cat <<EOD >/etc/docker/daemon.json
{
"registry-mirrors": ["http://127.0.0.1:65001"]
}
EOD
root@d7y-2:~# systemctl restart docker 
root@d7y-2:~# docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                      NAMES
b491e90489a5        dragonflyoss/dfclient:v0.3.0   "/dfclient/dfdaemo..."   28 seconds ago      Up 4 seconds        0.0.0.0:65001->65001/tcp   dragonfly-dfclient
root@d7y-2:~/.small-dragonfly/logs# cat dfdaemon.log
2019-03-30 01:18:21.331 INFO sign:1 : init...
2019-03-30 01:18:21.331 INFO sign:1 : rotate log routine start...
2019-03-30 01:18:21.338 INFO sign:1 : dfget version:
2019-03-30 01:18:21.338 ERRO sign:1 : init properties failed:open /etc/dragonfly/dfdaemon.yml: no such file or directory
2019-03-30 01:18:21.338 INFO sign:1 : init properties:{"Registries":[{"Schema":"https","Host":"registry.cn-qingdao.aliyuncs.com","Certs":null,"Regx":"(^localhost$)|(^127.0.0.1$)|(^127.0.0.1$)"}]}
2019-03-30 01:18:21.338 INFO sign:1 : init finish
2019-03-30 01:18:21.338 INFO sign:1 : start dfdaemon param: &{DfPath:/dfclient/dfget DFRepo:/root/.small-dragonfly/dfdaemon/data/ RateLimit:100M CallSystem:com_ops_dragonfly URLFilter:Signature&Expires&OSSAccessKeyId Notbs:true MaxProcs:4 Version:false Verbose:false HostIP:127.0.0.1 Port:65001 Registry:https://registry.cn-qingdao.aliyuncs.com DownRule: CertFile: KeyFile: TrustHosts:[] ConfigPath:/etc/dragonfly/dfdaemon.yml}
2019-03-30 01:18:21.338 INFO sign:1 : launch dfdaemon http server on 127.0.0.1:65001
root@d7y-2:~# docker login http://127.0.0.1:65001
Username: 
Password: 
Login Succeeded
// Enter your Aliyun account, password

//输入你的阿里云账号，密码 

root@d7y-2:~# docker login https://registry.cn-qingdao.aliyuncs.com 
Username: 
Password: 
Login Succeeded
// For insurance, login to Aliyun Registry address again

// 为保险起见，再登录阿里云registry地址 

// Check to see if it works

// 查看是否生效 

root@d7y-2:~/.small-dragonfly/logs# cat ~/.docker/config.json 
{
	"auths": {
		"127.0.0.1:65001": {
			"auth": "xxxxx="
		},
		"registry.cn-qingdao.aliyuncs.com": {
			"auth": "xxxxx="
		}
	}
}
root@d7y-2:~/.small-dragonfly/logs# docker pull d7y-test/nginx:alpine
Error response from daemon: repository d7y-test/nginx not found: does not exist or no pull access
// invalid by -- registry =registry.cn -qingdao.aliyuncs.com,--registry =https://registry.cn -qingdao.aliyuncs.com,--registry =http://registry.cn -qingdao.aliyuncs.com

// 尝试了--registry=registry.cn-qingdao.aliyuncs.com,--registry=https://registry.cn-qingdao.aliyuncs.com,--registry=http://registry.cn-qingdao.aliyuncs.com 均无效 

root@d7y-2:~/.small-dragonfly/logs# cat dfdaemon.log 
2019-03-30 01:39:36.441 INFO sign:1 : init...
2019-03-30 01:39:36.442 INFO sign:1 : rotate log routine start...
2019-03-30 01:39:36.448 INFO sign:1 : dfget version:
2019-03-30 01:39:36.448 ERRO sign:1 : init properties failed:open /etc/dragonfly/dfdaemon.yml: no such file or directory
2019-03-30 01:39:36.448 INFO sign:1 : init properties:{"Registries":[{"Schema":"https","Host":"registry.cn-qingdao.aliyuncs.com","Certs":null,"Regx":"(^localhost$)|(^127.0.0.1$)|(^127.0.0.1$)"}]}
2019-03-30 01:39:36.448 INFO sign:1 : init finish
2019-03-30 01:39:36.448 INFO sign:1 : start dfdaemon param: &{DfPath:/dfclient/dfget DFRepo:/root/.small-dragonfly/dfdaemon/data/ RateLimit:100M CallSystem:com_ops_dragonfly URLFilter:Signature&Expires&OSSAccessKeyId Notbs:true MaxProcs:4 Version:false Verbose:false HostIP:127.0.0.1 Port:65001 Registry:https://registry.cn-qingdao.aliyuncs.com DownRule: CertFile: KeyFile: TrustHosts:[] ConfigPath:/etc/dragonfly/dfdaemon.yml}
2019-03-30 01:39:36.448 INFO sign:1 : launch dfdaemon http server on 127.0.0.1:65001
2019-03-30 01:41:36.449 INFO sign:1 : scan repo and clean expired files
2019-03-30 01:41:36.449 INFO sign:1 : ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file
2019-03-30 01:43:36.449 INFO sign:1 : scan repo and clean expired files
2019-03-30 01:43:36.450 INFO sign:1 : ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file
2019-03-30 01:45:36.450 INFO sign:1 : scan repo and clean expired files
2019-03-30 01:45:36.450 INFO sign:1 : ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file
2019-03-30 01:47:36.450 INFO sign:1 : scan repo and clean expired files
2019-03-30 01:47:36.450 INFO sign:1 : ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file
2019-03-30 01:49:36.450 INFO sign:1 : scan repo and clean expired files
2019-03-30 01:49:36.451 INFO sign:1 : ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file
2019-03-30 01:49:51.759 INFO sign:1 : init...
2019-03-30 01:49:51.759 INFO sign:1 : rotate log routine start...
2019-03-30 01:49:51.763 INFO sign:1 : dfget version:
2019-03-30 01:49:51.763 ERRO sign:1 : init properties failed:open /etc/dragonfly/dfdaemon.yml: no such file or directory
2019-03-30 01:49:51.763 INFO sign:1 : init properties:{"Registries":[{"Schema":"http","Host":"registry.cn-qingdao.aliyuncs.com","Certs":null,"Regx":"(^localhost$)|(^127.0.0.1$)|(^127.0.0.1$)"}]}
2019-03-30 01:49:51.763 INFO sign:1 : init finish
2019-03-30 01:49:51.763 INFO sign:1 : start dfdaemon param: &{DfPath:/dfclient/dfget DFRepo:/root/.small-dragonfly/dfdaemon/data/ RateLimit:100M CallSystem:com_ops_dragonfly URLFilter:Signature&Expires&OSSAccessKeyId Notbs:true MaxProcs:4 Version:false Verbose:false HostIP:127.0.0.1 Port:65001 Registry:http://registry.cn-qingdao.aliyuncs.com DownRule: CertFile: KeyFile: TrustHosts:[] ConfigPath:/etc/dragonfly/dfdaemon.yml}
2019-03-30 01:49:51.763 INFO sign:1 : launch dfdaemon http server on 127.0.0.1:65001
2019-03-30 01:50:01.585 INFO sign:1 : init...
2019-03-30 01:50:01.585 INFO sign:1 : rotate log routine start...
2019-03-30 01:50:01.590 INFO sign:1 : dfget version:
2019-03-30 01:50:01.607 ERRO sign:1 : init properties failed:open /etc/dragonfly/dfdaemon.yml: no such file or directory
2019-03-30 01:50:01.607 INFO sign:1 : init properties:{"Registries":[{"Schema":"http","Host":"registry.cn-qingdao.aliyuncs.com","Certs":null,"Regx":"(^localhost$)|(^127.0.0.1$)|(^127.0.0.1$)"}]}
2019-03-30 01:50:01.607 INFO sign:1 : init finish
2019-03-30 01:50:01.607 INFO sign:1 : start dfdaemon param: &{DfPath:/dfclient/dfget DFRepo:/root/.small-dragonfly/dfdaemon/data/ RateLimit:100M CallSystem:com_ops_dragonfly URLFilter:Signature&Expires&OSSAccessKeyId Notbs:true MaxProcs:4 Version:false Verbose:false HostIP:127.0.0.1 Port:65001 Registry:http://registry.cn-qingdao.aliyuncs.com DownRule: CertFile: KeyFile: TrustHosts:[] ConfigPath:/etc/dragonfly/dfdaemon.yml}
2019-03-30 01:50:01.607 INFO sign:1 : launch dfdaemon http server on 127.0.0.1:65001
2019-03-30 01:52:14.004 INFO sign:1 : init...
2019-03-30 01:52:14.004 INFO sign:1 : rotate log routine start...
2019-03-30 01:52:14.011 INFO sign:1 : dfget version:
2019-03-30 01:52:14.011 ERRO sign:1 : init properties failed:open /etc/dragonfly/dfdaemon.yml: no such file or directory
2019-03-30 01:52:14.012 INFO sign:1 : init properties:{"Registries":[{"Schema":"http","Host":"registry.cn-qingdao.aliyuncs.com","Certs":null,"Regx":"(^localhost$)|(^127.0.0.1$)|(^127.0.0.1$)"}]}
2019-03-30 01:52:14.012 INFO sign:1 : init finish
2019-03-30 01:52:14.012 INFO sign:1 : start dfdaemon param: &{DfPath:/dfclient/dfget DFRepo:/root/.small-dragonfly/dfdaemon/data/ RateLimit:100M CallSystem:com_ops_dragonfly URLFilter:Signature&Expires&OSSAccessKeyId Notbs:true MaxProcs:4 Version:false Verbose:false HostIP:127.0.0.1 Port:65001 Registry:registry.cn-qingdao.aliyuncs.com DownRule: CertFile: KeyFile: TrustHosts:[] ConfigPath:/etc/dragonfly/dfdaemon.yml}
2019-03-30 01:52:14.012 INFO sign:1 : launch dfdaemon http server on 127.0.0.1:65001
2019-03-30 01:54:14.012 INFO sign:1 : scan repo and clean expired files
2019-03-30 01:54:14.012 INFO sign:1 : ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file

// Not work with registry.

// 加上registry也不行 

root@d7y-2:~/.small-dragonfly/logs# docker pull registry.cn-qingdao.aliyuncs.com/d7y-test/nginx:alpine
Error response from daemon: repository registry.cn-qingdao.aliyuncs.com/d7y-test/nginx not found: does not exist or no pull access
```
The two stations are all

// 两台均是

```bash

root@d7y-2:~/.small-dragonfly/logs# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 5
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-143-generic
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.859GiB
Name: d7y-2
ID: CWW5:3C6A:ZI63:G4OS:45XO:X66Y:MPHT:ZKYD:6PCT:TQRX:S5ZS:7GLY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://127.0.0.1:65001/
Live Restore Enabled: false

WARNING: No swap limit support


supernode app log
root@d7y-1:/data/dragonfly/supernode/logs# cat app.log 
2019-03-30 01:04:40.065 INFO  [      main] c.d.d.s.SuperNodeStarter       - Starting SuperNodeStarter on be7fb931db0b with PID 9 (/supernode.jar started by root in /)
2019-03-30 01:04:40.069 INFO  [      main] c.d.d.s.SuperNodeStarter       - No active profile set, falling back to default profiles: default
2019-03-30 01:04:42.151 INFO  [      main] c.d.d.s.c.SupernodeProperties  - init local ip of supernode, use ip:172.60.20.75
2019-03-30 01:04:42.253 INFO  [      main] c.d.d.s.c.SupernodeProperties  - cluster members: [{"downloadPort":8001,"ip":"localhost","registerPort":8002}]
2019-03-30 01:04:42.263 INFO  [      main] c.d.d.s.c.util.MonitorService  - available processors count is 4
2019-03-30 01:04:42.272 ERROR [  Thread-2] c.d.d.s.c.util.MonitorService  - process fields:null error
java.io.IOException: Cannot run program "tsar": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.dragonflyoss.dragonfly.supernode.common.util.MonitorService$1.run(MonitorService.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 common frames omitted
2019-03-30 01:04:43.507 INFO  [      main] c.d.d.s.SuperNodeStarter       - Started SuperNodeStarter in 3.906 seconds (JVM running for 4.59)
2019-03-30 01:04:49.472 INFO  [  spring-1] c.d.d.s.s.p.PreheatServiceImpl - deleteExpiresPreheatTask, count:0
2019-03-30 01:34:49.472 INFO  [  spring-7] c.d.d.s.s.p.PreheatServiceImpl - deleteExpiresPreheatTask, count:0
root@d7y-1:/data/dragonfly/supernode/logs# cat app.log 
2019-03-30 01:04:40.065 INFO  [      main] c.d.d.s.SuperNodeStarter       - Starting SuperNodeStarter on be7fb931db0b with PID 9 (/supernode.jar started by root in /)
2019-03-30 01:04:40.069 INFO  [      main] c.d.d.s.SuperNodeStarter       - No active profile set, falling back to default profiles: default
2019-03-30 01:04:42.151 INFO  [      main] c.d.d.s.c.SupernodeProperties  - init local ip of supernode, use ip:172.60.20.75
2019-03-30 01:04:42.253 INFO  [      main] c.d.d.s.c.SupernodeProperties  - cluster members: [{"downloadPort":8001,"ip":"localhost","registerPort":8002}]
2019-03-30 01:04:42.263 INFO  [      main] c.d.d.s.c.util.MonitorService  - available processors count is 4
2019-03-30 01:04:42.272 ERROR [  Thread-2] c.d.d.s.c.util.MonitorService  - process fields:null error
java.io.IOException: Cannot run program "tsar": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.dragonflyoss.dragonfly.supernode.common.util.MonitorService$1.run(MonitorService.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 common frames omitted
2019-03-30 01:04:43.507 INFO  [      main] c.d.d.s.SuperNodeStarter       - Started SuperNodeStarter in 3.906 seconds (JVM running for 4.59)
2019-03-30 01:04:49.472 INFO  [  spring-1] c.d.d.s.s.p.PreheatServiceImpl - deleteExpiresPreheatTask, count:0
2019-03-30 01:34:49.472 INFO  [  spring-7] c.d.d.s.s.p.PreheatServiceImpl - deleteExpiresPreheatTask, count:0
2019-03-30 02:04:49.476 INFO  [  spring-7] c.d.d.s.s.p.PreheatServiceImpl - deleteExpiresPreheatTask, count:0
```
***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by anjia0532** [comment]
已解决，换成 `docker pull dasemon:65001/ns/image:tag` 可以了
