### ISSUE TITLE
When dfget specifies -- node node, dfget still synchronizes old files after the supernode file is updated

### ISSUE THREAD

**Issue by huerlei** [dragonflyoss/Dragonfly#637]
## Question

问题描述：想测试一下，用dfget 同步过程中，supernode（也是file server）中的文件修改后，是否下次马上同步新文件，发现用dfget 同步的依旧是修改前的老文件，使用命令：
dfget --url  --output /data/qiyu/indexing.data --node ** -s 50M --totallimit 50M -b
dfget --version ：0.2.0
start download by dragonfly
====================start====================
progress[3092019/3092019   in 0.000s]
=====================end=====================
download SUCCESS(0) cost(0.191s) length:3092019 reason:0
fail to download indexing.data at Thu Jun 27 15:30:02 CST 2019
remote file length 3092024
local file length 3092019

**Comment by lowzj** [comment]
> supernode（也是file server）中的文件修改后

修改`supernode`本地的是没文件有用的，其是与文件源保持一致的。

> remote file length 3092024
> local file length 3092019

这里的 `remote` 和 `local` 具体是指什么。如果`remote`是`supernode`，从上面这两个数字来看，没有问题：
* `supernode`本地缓存文件数据大小 = 源文件大小 + 分片数 * 5
* 4MB以下的文件分片数都是1

@huerlei 可以使用md5来检验本地与文件源是否一致。

**Comment by huerlei** [comment]
**修改supernode本地文件的是没有效果的，其是与文件源保持一致的**。
这句不太懂是什么意思，是指supernode 上面的文件修改不起作用是吗
**这里的 remote 和 local 具体是指什么？**
remote file是supernode的文件， local 是用dfget 下载的文件大小，local file 和 remote file 大小不一致
**可以使用md5来检验本地与文件源是否一致**
MD5值，好像也是不同的，文件大小不一致

**Comment by huerlei** [comment]
@lowzj ,请问一下，对于supernode 上面的文件，怎样更新会让 dfget 同步正确的数据

**Comment by lowzj** [comment]
@huerlei supernode上的文件不是源文件，是加了分片信息的，大小跟dfget下载的文件肯定不一样

**Comment by huerlei** [comment]
好的，了解了，这个分片信息的文件，在什么情况下会更新呢

**Comment by lowzj** [comment]
@huerlei 源文件有变化时会更新

**Comment by huerlei** [comment]
![image](https://user-images.githubusercontent.com/13655961/60578543-f6648380-9db3-11e9-87b5-a17713266c9e.png)
好像和你说的有点不一样，我用dfget 从这个目录data下载的文件，是和源文件大小是一致的，我在supernode上面 echo test >> index.data 修改文件后，下载的就开始是老文件了

**Comment by huerlei** [comment]
@lowzj ,
![image](https://user-images.githubusercontent.com/13655961/60580242-53ae0400-9db7-11e9-8760-9fdf76cfa902.png)  nginx配置应该没有问题

**Comment by lowzj** [comment]
@huerlei 请详细的描述你的问题，以及复现步骤，我没看明白

**Comment by huerlei** [comment]
好的，是这样的，我部署的是物理机，部署了2个supernode（也是file server）节点和4台client，现在在其中一台client上，用/home/df-client/dfget --url http://$host/${REMOTE_PATH}/${REMOTE_FILE_NAME} --output ${DATA_DIR}/.${LOCAL_FILE_NAME}.temp${start_time} -s 50M --totallimit 50M -b --pattern p2p --node ${REMOTE_NODE} 命令同步supernode上面repo路径下data目录中的文件，开始同步正常，后面我手动修改了supernode上面的文件，之后就出现一直同步老文件的情况
dfclinet.log如下：
[2019-07-03 21:19:01,793] INFO sign:23911-1562159941.792 lineno:51 : cmd params:Namespace(callsystem=None, console=False, dfdaemon=False, filter=None, header=None, identifier=None, locallimit='50M', md5=None, node='10.16.180.98', notbs=False, output='/home/pizhou/.index.data.temp1562159941', pattern='p2p', showbar=True, timeout=None, totallimit='50M', url='http://10.16.180.98:8001/data/index.data', version=False),python version:sys.version_info(major=2, minor=7, micro=5, releaselevel='final', serial=0)
[2019-07-03 21:19:01,794] INFO sign:23911-1562159941.792 lineno:107 : target file path:/home/pizhou/.index.data.temp1562159941
[2019-07-03 21:19:01,798] INFO sign:23911-1562159941.792 lineno:133 : sysLang:UTF-8
[2019-07-03 21:19:01,798] INFO sign:23911-1562159941.792 lineno:137 : taskFileName:.index.data.temp1562159941-23911-1562159941.792 and cid:10.39.16.89-23911-1562159941.792
[2019-07-03 21:19:01,798] INFO sign:23911-1562159941.792 lineno:140 : task url:http://10.16.180.98:8001/data/index.data
[2019-07-03 21:19:01,803] INFO sign:23911-1562159941.792 lineno:60 : local http result:.index.data.temp1562159941-23911-1562159941.792@0.2.0 for path:/check/ and cost:0.004
[2019-07-03 21:19:01,805] INFO sign:23911-1562159941.792 lineno:64 : do register to 10.16.180.98,remainder:['10.16.180.98']
[2019-07-03 21:19:01,816] INFO sign:23911-1562159941.792 lineno:93 : do register result:{u'code': 200, u'data': {u'pieceSize': 4194304, u'fileLength': 9705, u'taskId': u'c799d750fa3693e3177f22a7bc53ff7a399d287eda93f98147172026721e4827'}} and cost 0.011
[2019-07-03 21:19:01,828] INFO sign:23911-1562159941.792 lineno:60 : local http result:52428800 for path:/rate/ and cost:0.002
[2019-07-03 21:19:01,847] INFO sign:23911-1562159941.792 lineno:173 : remaining writed piece count:0
[2019-07-03 21:19:01,850] INFO sign:23911-1562159941.792 lineno:178 : wait client writer finish cost 0.002,main qu size:0,client qu size:0
[2019-07-03 21:19:01,850] INFO sign:23911-1562159941.792 lineno:179 : current alive thread count:4
[2019-07-03 21:19:01,850] INFO sign:23911-1562159941.792 lineno:184 : super down md5:fa99e327978cf4ed9090310bae650df3
[2019-07-03 21:19:01,851] INFO sign:23911-1562159941.792 lineno:47 : compute raw md5:fa99e327978cf4ed9090310bae650df3 for file:/home/pizhou/.small-dragonfly/data/.index.data.temp1562159941-23911-1562159941.792 cost:0.000
[2019-07-03 21:19:01,851] INFO sign:23911-1562159941.792 lineno:109 : move src:/home/pizhou/.small-dragonfly/data/.index.data.temp1562159941-23911-1562159941.792 to dst:/home/pizhou/.index.data.temp1562159941 result:True cost:0.001
[2019-07-03 21:19:01,852] INFO sign:23911-1562159941.792 lineno:195 : download successfully from dragonfly
[2019-07-03 21:19:01,858] INFO sign:23911-1562159941.792 lineno:60 : local http result:success for path:/client/ and cost:0.002
[2019-07-03 21:19:01,858] INFO sign:23911-1562159941.792 lineno:94 : |c799d750fa3693e3177f22a7bc53ff7a399d287eda93f98147172026721e4827|http://10.16.180.98:8001/data/index.data|9705|9710|10.16.180.98|UNKNOWN|0.065|
[2019-07-03 21:19:01,859] INFO sign:23911-1562159941.792 lineno:111 : download SUCCESS cost:0.068s length:9705 reason:0

**Comment by huerlei** [comment]
@lowzj

**Comment by lowzj** [comment]
@huerlei 描述的是dfget下载的文件与更新后的源文件不一致，最好能够按以下步骤复现一下，提供如下信息和相关日志：
1. 第一次下载，使用md5sum或其他工具计算源文件md5值，及dfget下载后的文件md5值
2. 修改源文件，提供新的md5值
3. 再次使用dfget下载该文件，计算下载后的md5值

**Comment by huerlei** [comment]
@lowzj  我在dfget 命令中加入MD5校验的时候，会同步失败，这个是需要升级吗
dfclient.log
[2019-07-05 11:18:01,951] INFO sign:15455-1562296681.950 lineno:51 : cmd params:Namespace(callsystem=None, console=False, dfdaemon=False, filter=None, header=None, identifier=None, locallimit='50M', md5='MD5', node='10.16.180.98', notbs=False, output='/home/qiyu/.index.data.temp1562296681', pattern='p2p', showbar=True, timeout=None, totallimit='50M', url='http://10.16.180.98:8001/data/index.data', version=False),python version:sys.version_info(major=2, minor=7, micro=5, releaselevel='final', serial=0)
[2019-07-05 11:18:01,951] INFO sign:15455-1562296681.950 lineno:107 : target file path:/home/pizhou/.index.data.temp1562296681
[2019-07-05 11:18:01,954] INFO sign:15455-1562296681.950 lineno:133 : sysLang:UTF-8
[2019-07-05 11:18:01,954] INFO sign:15455-1562296681.950 lineno:137 : taskFileName:.index.data.temp1562296681-15455-1562296681.950 and cid:10.39.16.89-15455-1562296681.950
[2019-07-05 11:18:01,954] INFO sign:15455-1562296681.950 lineno:140 : task url:http://10.16.180.98:8001/data/index.data
[2019-07-05 11:18:01,958] INFO sign:15455-1562296681.950 lineno:60 : local http result:.index.data.temp1562296681-15455-1562296681.950@0.2.0 for path:/check/ and cost:0.003
[2019-07-05 11:18:01,958] INFO sign:15455-1562296681.950 lineno:64 : do register to 10.16.180.98,remainder:['10.16.180.98']
[2019-07-05 11:18:01,972] INFO sign:15455-1562296681.950 lineno:93 : do register result:{u'code': 200, u'data': {u'pieceSize': 4194304, u'fileLength': 9154, u'taskId': u'471678146f6c79414cff6ff96a56500edcd3fa95a63c87a9c34155045873664b'}} and cost 0.013
[2019-07-05 11:18:01,984] ERROR sign:15455-1562296681.950 lineno:119 : pull piece task fail:{u'msg': u'cdn status is fail', u'code': 604} and will migrate
[2019-07-05 11:18:01,985] INFO sign:15455-1562296681.950 lineno:64 : do register to 10.16.180.98,remainder:[]
[2019-07-05 11:18:01,996] INFO sign:15455-1562296681.950 lineno:93 : do register result:{u'code': 200, u'data': {u'pieceSize': 4194304, u'fileLength': 9154, u'taskId': u'471678146f6c79414cff6ff96a56500edcd3fa95a63c87a9c34155045873664b'}} and cost 0.011
[2019-07-05 11:18:02,005] ERROR sign:15455-1562296681.950 lineno:119 : pull piece task fail:{u'msg': u'cdn status is fail', u'code': 604} and will migrate
[2019-07-05 11:18:02,006] ERROR sign:15455-1562296681.950 lineno:243 : p2p fail

app.log
2019-07-05 11:22:01.882 INFO  [080-exec-1] c.d.d.s.s.impl.CdnManagerImpl  - do trigger cdn start for taskId:471678146f6c79414cff6ff96a56500edcd3fa95a63c87a9c34155045873664b,httpLen:9154
2019-07-05 11:22:01.883 INFO  [ Thread-15] c.d.d.s.s.impl.CdnManagerImpl  - do trigger cdn success for taskId:471678146f6c79414cff6ff96a56500edcd3fa95a63c87a9c34155045873664b
2019-07-05 11:22:01.886 INFO  [5-thread-6] c.d.d.s.s.cdn.Downloader       - taskId:471678146f6c79414cff6ff96a56500edcd3fa95a63c87a9c34155045873664b fileUrl:http://10.16.180.98:8001/data/entity_info_recindexing.data on downloader
2019-07-05 11:22:01.897 ERROR [5-thread-6] c.d.d.s.s.cdn.Downloader       - taskId:471678146f6c79414cff6ff96a56500edcd3fa95a63c87a9c34155045873664b url:http://10.16.180.98:8001/data/entity_info_recindexing.data file md5 not match expected:MD5 real:96760518d91a1a362c7882db1fb344e2
2019-07-05 11:22:01.900 INFO  [ Thread-16] c.d.d.s.s.i.CdnReporterImpl    - taskId:471678146f6c79414cff6ff96a56500edcd3fa95a63c87a9c34155045873664b fileLength:null status:FAIL from:write

**Comment by huerlei** [comment]
@lowzj 
**第一次下载，使用md5sum或其他工具计算源文件md5值，及dfget下载后的文件md5值**
第一次md5值都是009058a56637aed047d62cb85317697d
**修改源文件，提供新的md5值**
f0880cd52a38d53a628459978dfa21dc
再次使用dfget下载该文件，计算下载后的md5值
009058a56637aed047d62cb85317697d
client.log
[2019-07-05 14:47:01,413] INFO sign:2724-1562309221.412 lineno:51 : cmd params:Namespace(callsystem=None, console=False, dfdaemon=False, filter=None, header=None, identifier=None, locallimit='50M', md5=None, node='10.16.180.98', notbs=False, output='/home/pizhou/.index.data.temp1562309221', pattern='p2p', showbar=True, timeout=None, totallimit='50M', url='http://10.16.180.98:8001/data/index.data', version=False),python version:sys.version_info(major=2, minor=7, micro=5, releaselevel='final', serial=0)
[2019-07-05 14:47:01,414] INFO sign:2724-1562309221.412 lineno:107 : target file path:/home/pizhou/.index.data.temp1562309221
[2019-07-05 14:47:01,416] INFO sign:2724-1562309221.412 lineno:133 : sysLang:UTF-8
[2019-07-05 14:47:01,417] INFO sign:2724-1562309221.412 lineno:137 : taskFileName:.index.data.temp1562309221-2724-1562309221.412 and cid:10.39.16.90-2724-1562309221.412
[2019-07-05 14:47:01,417] INFO sign:2724-1562309221.412 lineno:140 : task url:http://10.16.180.98:8001/data/index.data
[2019-07-05 14:47:01,421] INFO sign:2724-1562309221.412 lineno:60 : local http result:.index.data.temp1562309221-2724-1562309221.412@0.2.0 for path:/check/ and cost:0.004
[2019-07-05 14:47:01,422] INFO sign:2724-1562309221.412 lineno:64 : do register to 10.16.180.98,remainder:['10.16.180.98']
[2019-07-05 14:47:01,438] INFO sign:2724-1562309221.412 lineno:93 : do register result:{u'code': 200, u'data': {u'pieceSize': 4194304, u'fileLength': 9216, u'taskId': u'c799d750fa3693e3177f22a7bc53ff7a399d287eda93f98147172026721e4827'}} and cost 0.016
[2019-07-05 14:47:01,454] INFO sign:2724-1562309221.412 lineno:60 : local http result:52428800 for path:/rate/ and cost:0.002
[2019-07-05 14:47:01,480] INFO sign:2724-1562309221.412 lineno:173 : remaining writed piece count:0
[2019-07-05 14:47:01,483] INFO sign:2724-1562309221.412 lineno:178 : wait client writer finish cost 0.002,main qu size:0,client qu size:0
[2019-07-05 14:47:01,483] INFO sign:2724-1562309221.412 lineno:179 : current alive thread count:4
[2019-07-05 14:47:01,484] INFO sign:2724-1562309221.412 lineno:184 : super down md5:009058a56637aed047d62cb85317697d
[2019-07-05 14:47:01,484] INFO sign:2724-1562309221.412 lineno:47 : compute raw md5:009058a56637aed047d62cb85317697d for file:/home/pizhou/.small-dragonfly/data/.index.data.temp1562309221-2724-1562309221.412 cost:0.000
[2019-07-05 14:47:01,485] INFO sign:2724-1562309221.412 lineno:109 : move src:/home/pizhou/.small-dragonfly/data/.index.data.temp1562309221-2724-1562309221.412 to dst:/home/pizhou/.index.data.temp1562309221 result:True cost:0.001
[2019-07-05 14:47:01,485] INFO sign:2724-1562309221.412 lineno:195 : download successfully from dragonfly
[2019-07-05 14:47:01,509] INFO sign:2724-1562309221.412 lineno:60 : local http result:success for path:/client/ and cost:0.002
[2019-07-05 14:47:01,510] INFO sign:2724-1562309221.412 lineno:94 : |c799d750fa3693e3177f22a7bc53ff7a399d287eda93f98147172026721e4827|http://10.16.180.98:8001/data/index.data|9216|9221|10.16.180.98|UNKNOWN|0.096|
[2019-07-05 14:47:01,510] INFO sign:2724-1562309221.412 lineno:111 : download SUCCESS cost:0.099s length:9216 reason:0

server.log

2019-07-05 14:39:19.496 INFO  [      main] c.d.d.s.SuperNodeStarter       - Starting SuperNodeStarter on recsys-general-monitor-online002-bjdxt9p.qiyi.virtual with PID 24983 (/data/Dragonfly/Dragonfly/src/supernode/target/supernode.jar started by root in /root)
2019-07-05 14:39:19.501 INFO  [      main] c.d.d.s.SuperNodeStarter       - No active profile set, falling back to default profiles: default
2019-07-05 14:39:21.171 INFO  [      main] c.d.d.s.c.SupernodeProperties  - init local ip of supernode, ip list:["10.16.180.98"], use ip:10.16.180.98
2019-07-05 14:39:21.213 INFO  [      main] c.d.d.s.c.SupernodeProperties  - cluster members: [{"downloadPort":8001,"ip":"localhost","registerPort":8002}]
2019-07-05 14:39:21.616 INFO  [      main] c.d.d.s.c.util.MonitorService  - available processors count is 8
2019-07-05 14:39:21.622 ERROR [  Thread-2] c.d.d.s.c.util.MonitorService  - process fields:null error
java.io.IOException: Cannot run program "tsar": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.dragonflyoss.dragonfly.supernode.common.util.MonitorService$1.run(MonitorService.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 common frames omitted
2019-07-05 14:39:22.306 INFO  [      main] c.d.d.s.SuperNodeStarter       - Started SuperNodeStarter in 3.21 seconds (JVM running for 3.839)
2019-07-05 14:39:28.270 INFO  [  spring-0] c.d.d.s.s.p.PreheatServiceImpl - deleteExpiresPreheatTask, count:0
2019-07-05 14:40:02.226 INFO  [080-exec-1] c.d.d.s.r.TaskRepository       - get file length:9216 from http client about taskId:c799d750fa3693e3177f22a7bc53ff7a399d287eda93f98147172026721e4827
2019-07-05 14:40:02.228 INFO  [080-exec-1] c.d.d.s.s.impl.CdnManagerImpl  - do trigger cdn start for taskId:c799d750fa3693e3177f22a7bc53ff7a399d287eda93f98147172026721e4827,httpLen:9216
2019-07-05 14:40:02.245 INFO  [  Thread-5] .d.s.c.u.NetConfigNotification - current rate limiter count is 1
2019-07-05 14:40:02.247 INFO  [  Thread-5] c.d.d.s.s.impl.CdnManagerImpl  - do trigger cdn success for taskId:c799d750fa3693e3177f22a7bc53ff7a399d287eda93f98147172026721e4827
2019-07-05 14:40:02.284 INFO  [5-thread-1] c.d.d.s.s.cdn.Downloader       - taskId:c799d750fa3693e3177f22a7bc53ff7a399d287eda93f98147172026721e4827 fileUrl:http://10.16.180.98:8001/data/index.data on downloader
2019-07-05 14:40:02.299 INFO  [7-thread-1] .d.s.c.u.NetConfigNotification - current rate limiter count is 2
2019-07-05 14:40:02.306 INFO  [  Thread-6] c.d.d.s.s.i.CdnReporterImpl    - taskId:c799d750fa3693e3177f22a7bc53ff7a399d287eda93f98147172026721e4827 fileLength:9221 status:SUCCESS from:local
2019-07-05 14:40:02.306 INFO  [  Thread-6] c.d.d.s.s.cdn.SuperWriter      - taskId:c799d750fa3693e3177f22a7bc53ff7a399d287eda93f98147172026721e4827 readCost:2,totalCost:22,fileLength:9216,realMd5:009058a56637aed047d62cb85317697d

**Comment by huerlei** [comment]
@lowzj ,可以帮忙看一下，这个问题能复现吗

**Comment by lowzj** [comment]
supernode在内存中会缓存下载任务的meta数据，同时将meta数据和文件数据落在本地硬盘上。
如果最近3分钟内无该任务的访问，supernode则会将meta信息剔除缓存，下次下载该文件的时候会从本地硬盘加载meta信息，同时向源站发送请求检查是否过期。
所以在最近3分钟内连续有客户端请求，同时源文件有更新，dragonfly网络中是不会更新的。

可以通过 dfget --identify 参数来区分同一个url但是不同内容的下载任务，比如 `--identify {file-update-timestamp}`。
