### ISSUE TITLE
[bug] register to node:  x.x.x.x error

### ISSUE THREAD

**Issue by wu1405** [dragonflyoss/Dragonfly#72]
Always get error  like this: 
 [2018-05-11 18:48:26,944] ERROR sign:59678-1526035671.512 lineno:81 : register to node:192.168.21.23 error

Traceback (most recent call last):
  File "/usr/local/df-client/component/httputil.py", line 67, in register
    schema, node), data=params, timeout=(2.0, 5.0))
  File "/usr/local/df-client/vendor/requests-2.18.4-py2.7.egg/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/df-client/vendor/requests-2.18.4-py2.7.egg/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/df-client/vendor/requests-2.18.4-py2.7.egg/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/df-client/vendor/requests-2.18.4-py2.7.egg/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='10.58.83.14', port=8002): Read timed out. (read timeout=5.0)
[2018-05-11 18:48:26,944] ERROR sign:59678-1526035671.512 lineno:243 : p2p fail
Traceback (most recent call last):
  File "/usr/local/df-client/core/fetcher.py", line 230, in run
    self.identifier)
  File "/usr/local/df-client/component/httputil.py", line 126, in pull_piece_task
    identifier)
  File "/usr/local/df-client/component/httputil.py", line 86, in register
    raise Exception("register result:%s" % result)
Exception: register result:None

**Comment by wu1405** [comment]
[2018-05-15 10:29:33,427] INFO sign:83846-1526351373.410 lineno:93 : do register result:{u'code': 200, u'data': {u'pieceSize': 15728640, u'fileLength': 7430897691, u'taskId': u'9a945882a7508e18f42eacda5e8c71c7c6e34e799fcddb92d509e69c94ac9d47'}} and cost 0.003
[2018-05-15 10:29:33,430] ERROR sign:83846-1526351373.410 lineno:119 : pull piece task fail:{u'msg': u'cdn status is fail', u'code': 604} and will migrate
[2018-05-15 10:29:33,430] INFO sign:83846-1526351373.410 lineno:64 : do register to 10.58.83.14,remainder:[]
[2018-05-15 10:29:33,431] INFO sign:83846-1526351373.410 lineno:93 : do register result:{u'code': 200, u'data': {u'pieceSize': 15728640, u'fileLength': 7430897691, u'taskId': u'9a945882a7508e18f42eacda5e8c71c7c6e34e799fcddb92d509e69c94ac9d47'}} and cost 0.002
[2018-05-15 10:29:33,433] ERROR sign:83846-1526351373.410 lineno:119 : pull piece task fail:{u'msg': u'cdn status is fail', u'code': 604} and will migrate
[2018-05-15 10:29:33,433] ERROR sign:83846-1526351373.410 lineno:243 : p2p fail
Traceback (most recent call last):
  File "/media/disk1/fordata/web_server/project/p2p/1.0/df-client/core/fetcher.py", line 230, in run
    self.identifier)
  File "/media/disk1/fordata/web_server/project/p2p/1.0/df-client/component/httputil.py", line 132, in pull_piece_task
    http_path, md5, identifier)
  File "/media/disk1/fordata/web_server/project/p2p/1.0/df-client/component/httputil.py", line 126, in pull_piece_task
    identifier)
  File "/media/disk1/fordata/web_server/project/p2p/1.0/df-client/component/httputil.py", line 86, in register
    raise Exception("register result:%s" % result)
Exception: register result:None
[2018-05-15 10:29:33,434] INFO sign:83846-1526351373.410 lineno:599 : download fail and not back source
[2018-05-15 10:29:33,437] INFO sign:83846-1526351373.410 lineno:60 : local http result:success for path:/client/ and cost:0.001
[2018-05-15 10:29:33,437] INFO sign:83846-1526351373.410 lineno:94 : |9a945882a7508e18f42eacda5e8c71c7c6e34e799fcddb92d509e69c94ac9d47|http://download.inner/test/testfile.tgz|7430897691|0|192.168.93.14|UNKNOWN|0.026|
[2018-05-15 10:29:33,437] INFO sign:83846-1526351373.410 lineno:111 : download FAIL cost:0.028s length:7430897691 reason:1003

**Comment by nonly** [comment]
supernode有啥日志么

**Comment by liuyaoli-xiaomi** [comment]
我这边也出现了类似的问题， 提示register node失败， dfget的日志显示如下：
![screenshot from 2018-06-25 19 34 06](https://user-images.githubusercontent.com/38308208/41848138-0ccad352-78af-11e8-838e-d2e813ca3868.png)

**Comment by liuyaoli-xiaomi** [comment]
将timeout=(2.0 5.0)更改成timeout=5后， node仍是register失败， 返回的code=607。 但是supernode没有任何异常日志输出
![screenshot from 2018-06-25 19 49 43](https://user-images.githubusercontent.com/38308208/41848720-ffe7a99c-78b0-11e8-9481-4d74e5e76462.png)
607是代表什么意思呢？

**Comment by nonly** [comment]
api文档里有
Other cases could happen:

1.  the task id might duplicate with an existing one. `606`
1.  the url might be invalid. `607`
1.  the access requires authentication. `608` or `609`

**Comment by liuyaoli-xiaomi** [comment]
第一个截图里的URL是session的postURL： http://localhost:8002/peer/registry
我理解这些url是代码自己拼起来的吧？ 为什么还会出现invalid的情况？ 是参数问题吗？ 
@nonly

**Comment by chenchaobing** [comment]
上面python的报错，应该是python版本的问题。
尝试执行以下命令，升级一下: 
pip install -U requests

**Comment by shenlanse** [comment]
我也是一直遇到各种问题，请问你们开源的这个版本到底  production ready了吗？ @allencloud @lowzj
